version: '3.5'

services:
  db_postgres:
    container_name: db_postgres
    ports:
      - "5432:5432"
    network_mode: 'host'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    image: postgres:16.2-alpine3.19