version: '3.5'

services:
  db_postgres:
    restart: "always"
    container_name: db_postgres
    ports:
      - "5432:5432"
#    network_mode: 'host'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    image: postgres:16.2-alpine3.19
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/001.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/002.sql