version: '3.5'

services:
  db_postgres:
    restart: "always"
    container_name: db_postgres
    ports:
      - "5432:5432"
    #    network_mode: 'host'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    image: postgres:16.2-alpine3.19
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/001.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/002.sql
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"