global:
  scrape_interval: 15s
scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 15s
#    scheme: http
##    target_port: 5000
#    static_configs:
#      - targets: [ '::5000' ]
#      - targets: [ 'localhost:9090' ]


  - job_name: 'spring_external_api_testing_lab'
    metrics_path: '/actuator/prometheus'
    static_configs:
#      - targets: [ 'localhost:5000' ]
      - targets: [ 'host.docker.internal:5000' ]
        labels:
          applications: 'My Spring Boot Application'
#    basic_auth:
#      username: 'chubaievskyi@gmail.com'
#      password: '123'
